import { NavLink } from 'react-router-dom';
const navLinks: { title: string; icon: string; href: string, category: string }[] = [
    {
        title: 'Dashboard',
        href: '/dashboard',
        icon: './dashboard.png',
        category: 'dashboard',
    },
    {
        title: 'Users',
        href: '/users',
        icon: './users.png',
        category: 'customer',
    },
    {
        title: 'Guarantors',
        href: '/#&',
        icon: './guarantor.png',
        category: 'customer',
    },
    {
        title: 'Loans',
        href: '/#&',
        icon: './loans.png',
        category: 'customer',
    },
    {
        title: 'Decision Models',
        href: '/#&',
        icon: './decision.png',
        category: 'customer',
    },
    {
        title: 'Savings',
        href: '/#&',
        icon: './savings.png',
        category: 'customer',
    },
    {
        title: 'Loan Requests',
        href: '/#&',
        icon: './loanRequest.png',
        category: 'customer',
    },
    {
        title: 'Whitelist',
        href: '/#&',
        icon: './whitelist.png',
        category: 'customer',
    },
    {
        title: 'Karma',
        href: '/#&',
        icon: './karma.png',
        category: 'customer',
    },
    {
        title: 'Organization',
        href: '/#&',
        icon: './organization.png',
        category: 'business',
    },
    {
        title: 'Loan Products',
        href: '/#&',
        icon: './loanProducts.png',
        category: 'business',
    },
    {
        title: 'Savings Products',
        href: '/#&',
        icon: './savingsProducts.png',
        category: 'business',
    },
    {
        title: 'Fees and Charges',
        href: '/#&',
        icon: './feesAndCharges.png',
        category: 'business',
    },
    {
        title: 'Transactions',
        href: '/#&',
        icon: './transactions.png',
        category: 'business',
    },
    {
        title: 'Services',
        href: '/#&',
        icon: './services.png',
        category: 'business',
    },
    {
        title: 'Service Account',
        href: '/#&',
        icon: './serviceAccount.png',
        category: 'business',
    },
    {
        title: 'Settlements',
        href: '/#&',
        icon: './settlements.png',
        category: 'business',
    },
    {
        title: 'Reports',
        href: '/#&',
        icon: './reports.png',
        category: 'business',
    },
    {
        title: 'Preferences',
        href: '/#&',
        icon: './preferences.png',
        category: 'settings',
    },
    {
        title: 'Fees and Pricing',
        href: '/#&',
        icon: './feesAndPricing.png',
        category: 'settings',
    },
    {
        title: 'Audit Logs',
        href: '/#&',
        icon: './auditLogs.png',
        category: 'settings',
    },
  ]